language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_install:
  - cp src/app/config/config.ts_example src/app/config/config.ts
#  - chmod a+x ./before_script.sh
  - sed -i "s/EnvapiKey/$apiKey/g" src/app/config/config.ts
  - sed -i "s/EnvauthDomain/$authDomain/g" src/app/config/config.ts
 # - sed -i "s/EnvdatabaseURL/$databaseURL/g" src/app/config/config.ts
  - sed -i "s/EnvstorageBucket/$storageBucket/g" src/app/config/config.ts
  - sed -i 's/EnvmessagingSenderId/$messagingSenderId/g' src/app/config/config.ts

install:
  - npm install

before_script:
  - npm install -g firebase-tools

script:
  - ng build --prod

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN} --project pgmeet-ba4f4
