language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_install:
  - cp src/app/config/config.ts_example src/app/config/config.ts
  - ./before_script.sh

install:
  - npm install

before_script:
  - npm install -g firebase-tools

script:
  - ng build --prod

after_success:
  - firebase deploy --token=${FIREBASE_TOKEN} --project pgmeet-ba4f4
